Slince\Shopify\Manager\Shop\Shop:
    properties:
        id:
            type: integer
        name:
            type: string
        email:
            type: string
        domain:
            type: string
        createdAt:
            type: DateTime<'Y-m-d\TH:i:sP'>
        updatedAt:
            type: DateTime<'Y-m-d\TH:i:sP'>
        province:
            type: string
        country:
            type: string
        address1:
            type: string
        zip:
            type: string
        city:
            type: string
        source:
            type: string
        phone:
            type: string
        customerEmail:
            type: string
        latitude:
            type: string
        longitude:
            type: string
        primaryLocationId:
            type: integer
        primaryLocale:
            type: string
        address2:
            type: string
        countryCode:
            type: string
        countryName:
            type: string
        currency:
            type: string
        timezone:
            type: string
        ianaTimezone:
            type: string
        shopOwner:
            type: string
        moneyFormat:
            type: string
        moneyWithCurrencyFormat:
            type: string
        weightUnit:
            type: string
        provinceCode:
            type: string
        taxesIncluded:
            type: boolean
        taxShipping:
            type: string
        countyTaxes:
            type: string
        planDisplayName:
            type: string
        planName:
            type: string
        hasDiscounts:
            type: boolean
        hasGiftCards:
            type: boolean
        myshopifyDomain:
            type: string
        googleAppsDomain:
            type: string
        googleAppsLoginEnabled:
            type: string
        moneyInEmailsFormat:
            type: string
        moneyWithCurrencyInEmailsFormat:
            type: string
        eligibleForPayments:
            type: boolean
        requiresExtraPaymentsAgreement:
            type: boolean
        passwordEnabled:
            type: boolean
        hasStoreFront:
            type: boolean
        eligibleForCardReaderGiveaway:
            type: boolean
        finances:
            type: boolean
        setupRequired:
            type: boolean
        forceSsl:
            type: boolean