Slince\Shopify\Manager\Policy\Policy:
    properties:
        id:
            type: integer
        title:
            type: string
        body:
            type: string
        handle:
            type: string
        createdAt:
            type: DateTime<'Y-m-d\TH:i:sP'>
        updatedAt:
            type: DateTime<'Y-m-d\TH:i:sP'>
        url:
            type: string