Slince\Shopify\Manager\Location\Location:
    properties:
        id:
            type: integer
        name:
            type: string
        deletedAt:
            type: DateTime<'Y-m-d\TH:i:sP'>
        address1:
            type: string
        address2:
            type: string
        city:
            type: string
        zip:
            type: string
        province:
            type: string
        country:
            type: string
        phone:
            type: string
        createdAt:
            type: DateTime<'Y-m-d\TH:i:sP'>
        updatedAt:
            type: DateTime<'Y-m-d\TH:i:sP'>
        countryCode:
            type: string
        countryName:
            type: string
        provinceCode:
            type: string
        adminGraphqlApiId:
            type: string